In [1]:
import pandas as pd

In [3]:
data = r"E:\automated_busy_downloads\comp0003\stock_journal\comp0003_stock_journal_2025-01-07 to 2025-01-22.xlsx"
df = pd.read_excel(data,skiprows=3)
df

,Date,Vch/Bill No,Material Centre,Item Details,Batch No,Batch Qty,Batch Narration,Qty. Generated,Unit Main,Price,Amount,Qty. Consumed,Unit Main.1,Price.1,Amount.1,Narration,Plant,Pur Inv No
0,2025-01-07,1,PGR,Nova Zyme (In Kgs),KB/A/NZ/0125/01,"3,030.950",NZ/01/01,3030.95,Kgs,0.0,0.0,0.0,NaN,0.000,0.000,NaN,NaN,NaN
1,2025-01-07,RM/STJL24/66,Raw Material Dept,2009 PM,KB2009RM0103L24,59.400,NaN,59.40,Kgs,328.0,19483.2,0.0,NaN,0.000,0.000,62.0,NaN,NaN
2,NaT,NaN,NaN,2009 RM,KB2009RM0103L24,60.000,NaN,0.00,NaN,0.0,0.0,60.0,Kgs,0.000,0.000,NaN,NaN,NaN
3,2025-01-08,RM/STJL24/67,Raw Material Dept,824 RM,KB824RM0101H24,720.000,NaN,720.00,Kgs,0.0,0.0,0.0,NaN,0.000,0.000,63.0,NaN,NaN
4,NaT,NaN,NaN,824 RM (Fruit),KB824RM0105I23,"1,845.000",NaN,0.00,NaN,0.0,0.0,1845.0,Kgs,184.113,339688.485,NaN,NaN,NaN
5,2025-01-15,2,PGR,Nova Zyme (In Kgs),KB/A/NZ/0125/01,"3,027.200",NZ/01/02,3027.20,Kgs,0.0,0.0,0.0,NaN,0.000,0.000,NaN,NaN,NaN
6,2025-01-18,FU3/STJL24/38,Formulation Unit 3,Balanstick (In Kgs),KB/A/BL/0125/01,"1,497.550",BL/01/01,1497.55,Kgs,0.0,0.0,0.0,NaN,0.000,0.000,NaN,NaN,NaN
7,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaT,NaN,NaN,NaN,NaN,NaN,Totals,8335.10,NaN,NaN,19483.2,1905.0,NaN,NaN,339688.485,NaN,NaN,NaN